import fs from 'fs';
import { matchSeeds } from './server/matchesData.js';

let sql = `-- Supabase SQL Schema for Futbol is Life

-- 1. Create Tables
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE matches (
  id INT PRIMARY KEY,
  home_team TEXT,
  away_team TEXT,
  home_flag TEXT,
  away_flag TEXT,
  stage TEXT NOT NULL,
  match_day INT,
  scheduled_at TIMESTAMPTZ,
  status TEXT DEFAULT 'scheduled',
  home_score INT,
  away_score INT,
  group_name TEXT
);

CREATE TABLE predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  match_id INT REFERENCES matches(id) ON DELETE CASCADE,
  home_score INT NOT NULL,
  away_score INT NOT NULL,
  points INT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, match_id)
);

CREATE TABLE arenas (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  owner_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE arena_members (
  arena_id TEXT REFERENCES arenas(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (arena_id, user_id)
);

-- 2. Automatic Profile Creation on Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 3. Automatic Points Calculation
CREATE OR REPLACE FUNCTION calculate_prediction_points()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status IN ('completed', 'live') THEN
    UPDATE predictions
    SET points = 
      CASE
        WHEN home_score = NEW.home_score AND away_score = NEW.away_score THEN 3
        WHEN sign(home_score - away_score) = sign(NEW.home_score - NEW.away_score) THEN 1
        ELSE 0
      END
    WHERE match_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_match_update
AFTER UPDATE OF home_score, away_score, status ON matches
FOR EACH ROW
EXECUTE FUNCTION calculate_prediction_points();

-- 4. Leaderboard View
CREATE OR REPLACE VIEW leaderboard AS
SELECT 
  p.id as user_id,
  p.display_name,
  COALESCE(SUM(pr.points), 0) as total_points,
  COUNT(pr.id) as predictions_count,
  COALESCE(SUM(CASE WHEN pr.points = 3 THEN 1 ELSE 0 END), 0) as exact_scores
FROM profiles p
LEFT JOIN predictions pr ON pr.user_id = p.id
LEFT JOIN matches m ON pr.match_id = m.id AND m.status IN ('completed', 'live')
GROUP BY p.id, p.display_name;

-- 5. Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE arenas ENABLE ROW LEVEL SECURITY;
ALTER TABLE arena_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Matches are viewable by everyone" ON matches FOR SELECT USING (true);
CREATE POLICY "Admins can update matches" ON matches FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)
);

CREATE POLICY "Predictions are viewable by everyone" ON predictions FOR SELECT USING (true);
CREATE POLICY "Users can insert their own predictions" ON predictions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own predictions" ON predictions FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Arenas are viewable by everyone" ON arenas FOR SELECT USING (true);
CREATE POLICY "Users can create arenas" ON arenas FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Arena members viewable by everyone" ON arena_members FOR SELECT USING (true);
CREATE POLICY "Users can join arenas" ON arena_members FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Initial Matches Data\n\n`;

matchSeeds.forEach(m => {
  const esc = str => str ? "'" + str.replace(/'/g, "''") + "'" : 'NULL';
  sql += `INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (${m.id}, ${esc(m.home_team)}, ${esc(m.away_team)}, ${esc(m.home_flag)}, ${esc(m.away_flag)}, ${esc(m.stage)}, ${m.match_day}, ${esc(m.scheduled_at)}, ${esc(m.status)}, ${m.home_score ?? 'NULL'}, ${m.away_score ?? 'NULL'}, ${esc(m.group_name)});\n`;
});

fs.writeFileSync('C:/Users/jibra/.gemini/antigravity/brain/572482ba-caf3-4ed6-839e-e1583dfbca7d/schema.sql', sql);
console.log('Generated schema.sql artifact');
