-- Supabase SQL Schema for Futbol is Life

-- 1. Create Tables
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  display_name TEXT NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE matches (
  id INT PRIMARY KEY,
  home_team TEXT,
  away_team TEXT,
  home_flag TEXT,
  away_flag TEXT,
  stage TEXT NOT NULL,
  match_day INT,
  scheduled_at TIMESTAMPTZ,
  status TEXT DEFAULT 'scheduled',
  home_score INT,
  away_score INT,
  group_name TEXT
);

CREATE TABLE predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  match_id INT REFERENCES matches(id) ON DELETE CASCADE,
  home_score INT NOT NULL,
  away_score INT NOT NULL,
  points INT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, match_id)
);

CREATE TABLE arenas (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE NOT NULL,
  owner_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE arena_members (
  arena_id TEXT REFERENCES arenas(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (arena_id, user_id)
);

-- 2. Automatic Profile Creation on Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name)
  VALUES (new.id, new.email, COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 3. Automatic Points Calculation
CREATE OR REPLACE FUNCTION calculate_prediction_points()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status IN ('completed', 'live') THEN
    UPDATE predictions
    SET points = 
      CASE
        WHEN home_score = NEW.home_score AND away_score = NEW.away_score THEN 3
        WHEN sign(home_score - away_score) = sign(NEW.home_score - NEW.away_score) THEN 1
        ELSE 0
      END
    WHERE match_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER on_match_update
AFTER UPDATE OF home_score, away_score, status ON matches
FOR EACH ROW
EXECUTE FUNCTION calculate_prediction_points();

-- 4. Leaderboard View
CREATE OR REPLACE VIEW leaderboard AS
SELECT 
  p.id as user_id,
  p.display_name,
  COALESCE(SUM(pr.points), 0) as total_points,
  COUNT(pr.id) as predictions_count,
  COALESCE(SUM(CASE WHEN pr.points = 3 THEN 1 ELSE 0 END), 0) as exact_scores
FROM profiles p
LEFT JOIN predictions pr ON pr.user_id = p.id
LEFT JOIN matches m ON pr.match_id = m.id AND m.status IN ('completed', 'live')
GROUP BY p.id, p.display_name;

-- 5. Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE arenas ENABLE ROW LEVEL SECURITY;
ALTER TABLE arena_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Matches are viewable by everyone" ON matches FOR SELECT USING (true);
CREATE POLICY "Admins can update matches" ON matches FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true)
);

CREATE POLICY "Predictions are viewable by everyone" ON predictions FOR SELECT USING (true);
CREATE POLICY "Users can insert their own predictions" ON predictions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own predictions" ON predictions FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Arenas are viewable by everyone" ON arenas FOR SELECT USING (true);
CREATE POLICY "Users can create arenas" ON arenas FOR INSERT WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "Arena members viewable by everyone" ON arena_members FOR SELECT USING (true);
CREATE POLICY "Users can join arenas" ON arena_members FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 6. Initial Matches Data

INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (1, 'Mexico', 'South Africa', '🇲🇽', '🇿🇦', 'group_stage', 1, '2026-06-11T19:00:00.000Z', 'completed', 2, 0, 'A');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (2, 'Korea Republic', 'Czechia', '🇰🇷', '🇨🇿', 'group_stage', 1, '2026-06-12T02:00:00.000Z', 'completed', 2, 1, 'A');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (3, 'Canada', 'Bosnia-Herzegovina', '🇨🇦', '🇧🇦', 'group_stage', 1, '2026-06-12T19:00:00.000Z', 'completed', 1, 1, 'B');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (4, 'United States', 'Paraguay', '🇺🇸', '🇵🇾', 'group_stage', 1, '2026-06-13T01:00:00.000Z', 'completed', 4, 1, 'C');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (5, 'Qatar', 'Switzerland', '🇶🇦', '🇨🇭', 'group_stage', 1, '2026-06-13T19:00:00.000Z', 'completed', 1, 1, 'B');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (6, 'Brazil', 'Morocco', '🇧🇷', '🇲🇦', 'group_stage', 1, '2026-06-13T22:00:00.000Z', 'completed', 1, 1, 'F');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (7, 'Haiti', 'Scotland', '🇭🇹', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'group_stage', 1, '2026-06-14T01:00:00.000Z', 'completed', 0, 1, 'F');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (8, 'Australia', 'Türkiye', '🇦🇺', '🇹🇷', 'group_stage', 1, '2026-06-14T04:00:00.000Z', 'completed', 2, 0, 'C');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (9, 'Germany', 'Curaçao', '🇩🇪', '🇨🇼', 'group_stage', 1, '2026-06-14T17:00:00.000Z', 'completed', 7, 1, 'D');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (10, 'Netherlands', 'Japan', '🇳🇱', '🇯🇵', 'group_stage', 1, '2026-06-14T20:00:00.000Z', 'completed', 2, 2, 'E');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (11, 'Ivory Coast', 'Ecuador', '🇨🇮', '🇪🇨', 'group_stage', 1, '2026-06-14T23:00:00.000Z', 'completed', 1, 0, 'D');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (12, 'Sweden', 'Tunisia', '🇸🇪', '🇹🇳', 'group_stage', 1, '2026-06-15T02:00:00.000Z', 'completed', 5, 1, 'E');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (13, 'Spain', 'Cape Verde', '🇪🇸', '🇨🇻', 'group_stage', 1, '2026-06-15T17:00:00.000Z', 'completed', 0, 0, 'G');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (15, 'Saudi Arabia', 'Uruguay', '🇸🇦', '🇺🇾', 'group_stage', 1, '2026-06-15T22:00:00.000Z', 'scheduled', NULL, NULL, 'G');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (14, 'Belgium', 'Egypt', '🇧🇪', '🇪🇬', 'group_stage', 1, '2026-06-15T22:00:00.000Z', 'scheduled', NULL, NULL, 'H');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (16, 'Iran', 'New Zealand', '🇮🇷', '🇳🇿', 'group_stage', 1, '2026-06-16T04:00:00.000Z', 'scheduled', NULL, NULL, 'H');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (17, 'France', 'Senegal', '🇫🇷', '🇸🇳', 'group_stage', 1, '2026-06-16T19:00:00.000Z', 'scheduled', NULL, NULL, 'I');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (18, 'Iraq', 'Norway', '🇮🇶', '🇳🇴', 'group_stage', 1, '2026-06-16T22:00:00.000Z', 'scheduled', NULL, NULL, 'I');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (19, 'Argentina', 'Algeria', '🇦🇷', '🇩🇿', 'group_stage', 1, '2026-06-17T01:00:00.000Z', 'scheduled', NULL, NULL, 'J');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (20, 'Austria', 'Jordan', '🇦🇹', '🇯🇴', 'group_stage', 1, '2026-06-17T04:00:00.000Z', 'scheduled', NULL, NULL, 'J');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (21, 'Portugal', 'DR Congo', '🇵🇹', '🇨🇩', 'group_stage', 1, '2026-06-17T17:00:00.000Z', 'scheduled', NULL, NULL, 'L');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (22, 'England', 'Croatia', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🇭🇷', 'group_stage', 1, '2026-06-17T20:00:00.000Z', 'scheduled', NULL, NULL, 'K');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (23, 'Ghana', 'Panama', '🇬🇭', '🇵🇦', 'group_stage', 1, '2026-06-17T23:00:00.000Z', 'scheduled', NULL, NULL, 'K');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (24, 'Uzbekistan', 'Colombia', '🇺🇿', '🇨🇴', 'group_stage', 1, '2026-06-18T02:00:00.000Z', 'scheduled', NULL, NULL, 'L');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (25, 'Czechia', 'South Africa', '🇨🇿', '🇿🇦', 'group_stage', 2, '2026-06-18T16:00:00.000Z', 'scheduled', NULL, NULL, 'A');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (26, 'Switzerland', 'Bosnia-Herzegovina', '🇨🇭', '🇧🇦', 'group_stage', 2, '2026-06-18T19:00:00.000Z', 'scheduled', NULL, NULL, 'B');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (27, 'Canada', 'Qatar', '🇨🇦', '🇶🇦', 'group_stage', 2, '2026-06-18T22:00:00.000Z', 'scheduled', NULL, NULL, 'B');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (28, 'Mexico', 'Korea Republic', '🇲🇽', '🇰🇷', 'group_stage', 2, '2026-06-19T03:00:00.000Z', 'scheduled', NULL, NULL, 'A');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (29, 'United States', 'Australia', '🇺🇸', '🇦🇺', 'group_stage', 2, '2026-06-19T19:00:00.000Z', 'scheduled', NULL, NULL, 'C');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (30, 'Scotland', 'Morocco', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', '🇲🇦', 'group_stage', 2, '2026-06-19T22:00:00.000Z', 'scheduled', NULL, NULL, 'F');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (31, 'Brazil', 'Haiti', '🇧🇷', '🇭🇹', 'group_stage', 2, '2026-06-20T01:00:00.000Z', 'scheduled', NULL, NULL, 'F');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (32, 'Türkiye', 'Paraguay', '🇹🇷', '🇵🇾', 'group_stage', 2, '2026-06-20T04:00:00.000Z', 'scheduled', NULL, NULL, 'C');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (33, 'Netherlands', 'Sweden', '🇳🇱', '🇸🇪', 'group_stage', 2, '2026-06-20T17:00:00.000Z', 'scheduled', NULL, NULL, 'E');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (34, 'Germany', 'Ivory Coast', '🇩🇪', '🇨🇮', 'group_stage', 2, '2026-06-20T20:00:00.000Z', 'scheduled', NULL, NULL, 'D');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (35, 'Ecuador', 'Curaçao', '🇪🇨', '🇨🇼', 'group_stage', 2, '2026-06-21T00:00:00.000Z', 'scheduled', NULL, NULL, 'D');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (36, 'Tunisia', 'Japan', '🇹🇳', '🇯🇵', 'group_stage', 2, '2026-06-21T04:00:00.000Z', 'scheduled', NULL, NULL, 'E');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (37, 'Spain', 'Saudi Arabia', '🇪🇸', '🇸🇦', 'group_stage', 2, '2026-06-21T16:00:00.000Z', 'scheduled', NULL, NULL, 'G');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (38, 'Belgium', 'Iran', '🇧🇪', '🇮🇷', 'group_stage', 2, '2026-06-21T19:00:00.000Z', 'scheduled', NULL, NULL, 'H');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (39, 'Uruguay', 'Cape Verde', '🇺🇾', '🇨🇻', 'group_stage', 2, '2026-06-21T22:00:00.000Z', 'scheduled', NULL, NULL, 'G');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (40, 'New Zealand', 'Egypt', '🇳🇿', '🇪🇬', 'group_stage', 2, '2026-06-22T01:00:00.000Z', 'scheduled', NULL, NULL, 'H');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (41, 'Argentina', 'Austria', '🇦🇷', '🇦🇹', 'group_stage', 2, '2026-06-22T17:00:00.000Z', 'scheduled', NULL, NULL, 'J');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (42, 'France', 'Iraq', '🇫🇷', '🇮🇶', 'group_stage', 2, '2026-06-22T21:00:00.000Z', 'scheduled', NULL, NULL, 'I');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (43, 'Norway', 'Senegal', '🇳🇴', '🇸🇳', 'group_stage', 2, '2026-06-23T00:00:00.000Z', 'scheduled', NULL, NULL, 'I');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (44, 'Jordan', 'Algeria', '🇯🇴', '🇩🇿', 'group_stage', 2, '2026-06-23T03:00:00.000Z', 'scheduled', NULL, NULL, 'J');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (45, 'Portugal', 'Uzbekistan', '🇵🇹', '🇺🇿', 'group_stage', 2, '2026-06-23T17:00:00.000Z', 'scheduled', NULL, NULL, 'L');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (46, 'England', 'Ghana', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🇬🇭', 'group_stage', 2, '2026-06-23T20:00:00.000Z', 'scheduled', NULL, NULL, 'K');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (47, 'Panama', 'Croatia', '🇵🇦', '🇭🇷', 'group_stage', 2, '2026-06-23T23:00:00.000Z', 'scheduled', NULL, NULL, 'K');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (48, 'Colombia', 'DR Congo', '🇨🇴', '🇨🇩', 'group_stage', 2, '2026-06-24T02:00:00.000Z', 'scheduled', NULL, NULL, 'L');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (50, 'Bosnia-Herzegovina', 'Qatar', '🇧🇦', '🇶🇦', 'group_stage', 3, '2026-06-24T19:00:00.000Z', 'scheduled', NULL, NULL, 'B');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (49, 'Switzerland', 'Canada', '🇨🇭', '🇨🇦', 'group_stage', 3, '2026-06-24T19:00:00.000Z', 'scheduled', NULL, NULL, 'B');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (52, 'Morocco', 'Haiti', '🇲🇦', '🇭🇹', 'group_stage', 3, '2026-06-24T22:00:00.000Z', 'scheduled', NULL, NULL, 'F');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (51, 'Scotland', 'Brazil', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', '🇧🇷', 'group_stage', 3, '2026-06-24T22:00:00.000Z', 'scheduled', NULL, NULL, 'F');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (53, 'Czechia', 'Mexico', '🇨🇿', '🇲🇽', 'group_stage', 3, '2026-06-25T01:00:00.000Z', 'scheduled', NULL, NULL, 'A');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (54, 'South Africa', 'Korea Republic', '🇿🇦', '🇰🇷', 'group_stage', 3, '2026-06-25T01:00:00.000Z', 'scheduled', NULL, NULL, 'A');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (56, 'Curaçao', 'Ivory Coast', '🇨🇼', '🇨🇮', 'group_stage', 3, '2026-06-25T20:00:00.000Z', 'scheduled', NULL, NULL, 'D');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (55, 'Ecuador', 'Germany', '🇪🇨', '🇩🇪', 'group_stage', 3, '2026-06-25T20:00:00.000Z', 'scheduled', NULL, NULL, 'D');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (57, 'Japan', 'Sweden', '🇯🇵', '🇸🇪', 'group_stage', 3, '2026-06-25T23:00:00.000Z', 'scheduled', NULL, NULL, 'E');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (58, 'Tunisia', 'Netherlands', '🇹🇳', '🇳🇱', 'group_stage', 3, '2026-06-25T23:00:00.000Z', 'scheduled', NULL, NULL, 'E');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (59, 'Türkiye', 'United States', '🇹🇷', '🇺🇸', 'group_stage', 3, '2026-06-26T02:00:00.000Z', 'scheduled', NULL, NULL, 'C');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (60, 'Paraguay', 'Australia', '🇵🇾', '🇦🇺', 'group_stage', 3, '2026-06-26T02:00:00.000Z', 'scheduled', NULL, NULL, 'C');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (62, 'Senegal', 'Iraq', '🇸🇳', '🇮🇶', 'group_stage', 3, '2026-06-26T19:00:00.000Z', 'scheduled', NULL, NULL, 'I');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (61, 'Norway', 'France', '🇳🇴', '🇫🇷', 'group_stage', 3, '2026-06-26T19:00:00.000Z', 'scheduled', NULL, NULL, 'I');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (63, 'Cape Verde', 'Saudi Arabia', '🇨🇻', '🇸🇦', 'group_stage', 3, '2026-06-27T00:00:00.000Z', 'scheduled', NULL, NULL, 'G');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (64, 'Uruguay', 'Spain', '🇺🇾', '🇪🇸', 'group_stage', 3, '2026-06-27T00:00:00.000Z', 'scheduled', NULL, NULL, 'G');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (66, 'New Zealand', 'Belgium', '🇳🇿', '🇧🇪', 'group_stage', 3, '2026-06-27T03:00:00.000Z', 'scheduled', NULL, NULL, 'H');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (65, 'Egypt', 'Iran', '🇪🇬', '🇮🇷', 'group_stage', 3, '2026-06-27T03:00:00.000Z', 'scheduled', NULL, NULL, 'H');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (68, 'Croatia', 'Ghana', '🇭🇷', '🇬🇭', 'group_stage', 3, '2026-06-27T21:00:00.000Z', 'scheduled', NULL, NULL, 'K');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (67, 'Panama', 'England', '🇵🇦', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'group_stage', 3, '2026-06-27T21:00:00.000Z', 'scheduled', NULL, NULL, 'K');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (69, 'Colombia', 'Portugal', '🇨🇴', '🇵🇹', 'group_stage', 3, '2026-06-27T23:30:00.000Z', 'scheduled', NULL, NULL, 'L');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (70, 'DR Congo', 'Uzbekistan', '🇨🇩', '🇺🇿', 'group_stage', 3, '2026-06-27T23:30:00.000Z', 'scheduled', NULL, NULL, 'L');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (72, 'Jordan', 'Argentina', '🇯🇴', '🇦🇷', 'group_stage', 3, '2026-06-28T02:00:00.000Z', 'scheduled', NULL, NULL, 'J');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (71, 'Algeria', 'Austria', '🇩🇿', '🇦🇹', 'group_stage', 3, '2026-06-28T02:00:00.000Z', 'scheduled', NULL, NULL, 'J');
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (73, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-28T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (74, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-28T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (75, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-29T00:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (76, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-29T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (77, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-29T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (78, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-30T00:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (79, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-30T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (80, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-06-30T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (81, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-01T00:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (82, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-01T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (83, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-01T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (84, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-02T00:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (85, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-02T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (86, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-02T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (87, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-03T00:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (88, NULL, NULL, NULL, NULL, 'round_of_32', null, '2026-07-03T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (89, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-04T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (90, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-04T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (91, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-05T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (92, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-05T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (93, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-06T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (94, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-06T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (95, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-07T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (96, NULL, NULL, NULL, NULL, 'round_of_16', null, '2026-07-07T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (97, NULL, NULL, NULL, NULL, 'quarterfinals', null, '2026-07-10T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (98, NULL, NULL, NULL, NULL, 'quarterfinals', null, '2026-07-10T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (99, NULL, NULL, NULL, NULL, 'quarterfinals', null, '2026-07-12T18:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (100, NULL, NULL, NULL, NULL, 'quarterfinals', null, '2026-07-12T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (101, NULL, NULL, NULL, NULL, 'semifinals', null, '2026-07-14T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (102, NULL, NULL, NULL, NULL, 'semifinals', null, '2026-07-15T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
INSERT INTO matches (id, home_team, away_team, home_flag, away_flag, stage, match_day, scheduled_at, status, home_score, away_score, group_name) VALUES (103, NULL, NULL, NULL, NULL, 'final', null, '2026-07-19T21:00:00.000Z', 'scheduled', NULL, NULL, NULL);
