// Country name → ISO 3166-1 alpha-2 code mapping for flagcdn.com
// Usage: https://flagcdn.com/32x24/${code}.png
export const COUNTRY_CODES = {
  // WC 2026 Teams
  'Mexico': 'mx',
  'South Africa': 'za',
  'Korea Republic': 'kr',
  'South Korea': 'kr',
  'Czechia': 'cz',
  'Czech Republic': 'cz',
  'Canada': 'ca',
  'Bosnia-Herzegovina': 'ba',
  'Bosnia and Herzegovina': 'ba',
  'United States': 'us',
  'USA': 'us',
  'Paraguay': 'py',
  'Qatar': 'qa',
  'Switzerland': 'ch',
  'Brazil': 'br',
  'Morocco': 'ma',
  'Haiti': 'ht',
  'Scotland': 'gb-sct',
  'Australia': 'au',
  'Türkiye': 'tr',
  'Turkey': 'tr',
  'Germany': 'de',
  'Curaçao': 'cw',
  'Netherlands': 'nl',
  'Japan': 'jp',
  'Argentina': 'ar',
  'Portugal': 'pt',
  'Spain': 'es',
  'France': 'fr',
  'England': 'gb-eng',
  'Italy': 'it',
  'Belgium': 'be',
  'Uruguay': 'uy',
  'Croatia': 'hr',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Senegal': 'sn',
  'Ghana': 'gh',
  'Nigeria': 'ng',
  'Cameroon': 'cm',
  "Côte d'Ivoire": 'ci',
  'Ivory Coast': 'ci',
  'Tunisia': 'tn',
  'Egypt': 'eg',
  'Mali': 'ml',
  'Guinea': 'gn',
  'Algeria': 'dz',
  'Congo': 'cg',
  'DR Congo': 'cd',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Jordan': 'jo',
  'Indonesia': 'id',
  'New Zealand': 'nz',
  'Panama': 'pa',
  'Honduras': 'hn',
  'Costa Rica': 'cr',
  'Jamaica': 'jm',
  'Venezuela': 've',
  'Bolivia': 'bo',
  'Chile': 'cl',
  'Peru': 'pe',
  'Guatemala': 'gt',
  'El Salvador': 'sv',
  'Cuba': 'cu',
  'Trinidad and Tobago': 'tt',
  'Poland': 'pl',
  'Serbia': 'rs',
  'Denmark': 'dk',
  'Austria': 'at',
  'Hungary': 'hu',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Albania': 'al',
  'Greece': 'gr',
  'Romania': 'ro',
  'Ukraine': 'ua',
  'Wales': 'gb-wls',
  'Sweden': 'se',
  'Norway': 'no',
  'Finland': 'fi',
  'Iceland': 'is',
  'Russia': 'ru',
  'China': 'cn',
  'Thailand': 'th',
  'Vietnam': 'vn',
  'Uzbekistan': 'uz',
  'Bahrain': 'bh',
  'Oman': 'om',
  'United Arab Emirates': 'ae',
  'Kuwait': 'kw',
  'Palestine': 'ps',
  'Kyrgyzstan': 'kg',
  'Tajikistan': 'tj',
  'Turkmenistan': 'tm',
  'Taiwan': 'tw',
  'Philippines': 'ph',
  'Malaysia': 'my',
  'Myanmar': 'mm',
  'Singapore': 'sg',
  'Bangladesh': 'bd',
  'Nepal': 'np',
  'Sri Lanka': 'lk',
  'Pakistan': 'pk',
  'Afghanistan': 'af',
  'Liberia': 'lr',
  'Angola': 'ao',
  'Tanzania': 'tz',
  'Kenya': 'ke',
  'Zambia': 'zm',
  'Zimbabwe': 'zw',
  'Mozambique': 'mz',
  'Namibia': 'na',
  'Botswana': 'bw',
  'Rwanda': 'rw',
  'Uganda': 'ug',
  'Ethiopia': 'et',
  'Sudan': 'sd',
  'Cape Verde': 'cv',
  'Comoros': 'km',
  'Benin': 'bj',
  'Burkina Faso': 'bf',
  'Mauritania': 'mr',
  'Gabon': 'ga',
  'Equatorial Guinea': 'gq',
  'Mozambique': 'mz',
  'Eswatini': 'sz',
  'Libya': 'ly',
};

/**
 * Get the flagcdn.com URL for a country name
 * @param {string} name - Country name
 * @param {number} size - Width: 20, 24, 40, 48, 80 etc.
 */
export function getFlagUrl(name, size = 40) {
  if (!name || name === 'TBD') return null;
  const code = COUNTRY_CODES[name];
  if (!code) return null;
  return `https://flagcdn.com/${size}x${Math.round(size * 0.75)}.png?country=${code}`;
}

/**
 * Get the flagcdn.com SVG URL for a country name
 */
export function getFlagSvgUrl(name) {
  if (!name || name === 'TBD') return null;
  const code = COUNTRY_CODES[name];
  if (!code) return null;
  return `https://flagcdn.com/${code}.svg`;
}
