export const matchSeeds = [
  {
    "id": 1,
    "home_team": "Mexico",
    "away_team": "South Africa",
    "home_flag": "🇲🇽",
    "away_flag": "🇿🇦",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-11T19:00:00.000Z",
    "status": "completed",
    "home_score": 2,
    "away_score": 0,
    "group_name": "A"
  },
  {
    "id": 2,
    "home_team": "Korea Republic",
    "away_team": "Czechia",
    "home_flag": "🇰🇷",
    "away_flag": "🇨🇿",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-12T02:00:00.000Z",
    "status": "completed",
    "home_score": 2,
    "away_score": 1,
    "group_name": "A"
  },
  {
    "id": 3,
    "home_team": "Canada",
    "away_team": "Bosnia-Herzegovina",
    "home_flag": "🇨🇦",
    "away_flag": "🇧🇦",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-12T19:00:00.000Z",
    "status": "completed",
    "home_score": 1,
    "away_score": 1,
    "group_name": "B"
  },
  {
    "id": 4,
    "home_team": "United States",
    "away_team": "Paraguay",
    "home_flag": "🇺🇸",
    "away_flag": "🇵🇾",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-13T01:00:00.000Z",
    "status": "completed",
    "home_score": 4,
    "away_score": 1,
    "group_name": "C"
  },
  {
    "id": 5,
    "home_team": "Qatar",
    "away_team": "Switzerland",
    "home_flag": "🇶🇦",
    "away_flag": "🇨🇭",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-13T19:00:00.000Z",
    "status": "completed",
    "home_score": 1,
    "away_score": 1,
    "group_name": "B"
  },
  {
    "id": 6,
    "home_team": "Brazil",
    "away_team": "Morocco",
    "home_flag": "🇧🇷",
    "away_flag": "🇲🇦",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-13T22:00:00.000Z",
    "status": "completed",
    "home_score": 1,
    "away_score": 1,
    "group_name": "F"
  },
  {
    "id": 7,
    "home_team": "Haiti",
    "away_team": "Scotland",
    "home_flag": "🇭🇹",
    "away_flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-14T01:00:00.000Z",
    "status": "completed",
    "home_score": 0,
    "away_score": 1,
    "group_name": "F"
  },
  {
    "id": 8,
    "home_team": "Australia",
    "away_team": "Türkiye",
    "home_flag": "🇦🇺",
    "away_flag": "🇹🇷",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-14T04:00:00.000Z",
    "status": "completed",
    "home_score": 2,
    "away_score": 0,
    "group_name": "C"
  },
  {
    "id": 9,
    "home_team": "Germany",
    "away_team": "Curaçao",
    "home_flag": "🇩🇪",
    "away_flag": "🇨🇼",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-14T17:00:00.000Z",
    "status": "completed",
    "home_score": 7,
    "away_score": 1,
    "group_name": "D"
  },
  {
    "id": 10,
    "home_team": "Netherlands",
    "away_team": "Japan",
    "home_flag": "🇳🇱",
    "away_flag": "🇯🇵",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-14T20:00:00.000Z",
    "status": "completed",
    "home_score": 2,
    "away_score": 2,
    "group_name": "E"
  },
  {
    "id": 11,
    "home_team": "Ivory Coast",
    "away_team": "Ecuador",
    "home_flag": "🇨🇮",
    "away_flag": "🇪🇨",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-14T23:00:00.000Z",
    "status": "completed",
    "home_score": 1,
    "away_score": 0,
    "group_name": "D"
  },
  {
    "id": 12,
    "home_team": "Sweden",
    "away_team": "Tunisia",
    "home_flag": "🇸🇪",
    "away_flag": "🇹🇳",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-15T02:00:00.000Z",
    "status": "completed",
    "home_score": 5,
    "away_score": 1,
    "group_name": "E"
  },
  {
    "id": 13,
    "home_team": "Spain",
    "away_team": "Cape Verde",
    "home_flag": "🇪🇸",
    "away_flag": "🇨🇻",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-15T17:00:00.000Z",
    "status": "completed",
    "home_score": 0,
    "away_score": 0,
    "group_name": "G"
  },
  {
    "id": 15,
    "home_team": "Saudi Arabia",
    "away_team": "Uruguay",
    "home_flag": "🇸🇦",
    "away_flag": "🇺🇾",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-15T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "G"
  },
  {
    "id": 14,
    "home_team": "Belgium",
    "away_team": "Egypt",
    "home_flag": "🇧🇪",
    "away_flag": "🇪🇬",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-15T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "H"
  },
  {
    "id": 16,
    "home_team": "Iran",
    "away_team": "New Zealand",
    "home_flag": "🇮🇷",
    "away_flag": "🇳🇿",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-16T04:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "H"
  },
  {
    "id": 17,
    "home_team": "France",
    "away_team": "Senegal",
    "home_flag": "🇫🇷",
    "away_flag": "🇸🇳",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-16T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "I"
  },
  {
    "id": 18,
    "home_team": "Iraq",
    "away_team": "Norway",
    "home_flag": "🇮🇶",
    "away_flag": "🇳🇴",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-16T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "I"
  },
  {
    "id": 19,
    "home_team": "Argentina",
    "away_team": "Algeria",
    "home_flag": "🇦🇷",
    "away_flag": "🇩🇿",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-17T01:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "J"
  },
  {
    "id": 20,
    "home_team": "Austria",
    "away_team": "Jordan",
    "home_flag": "🇦🇹",
    "away_flag": "🇯🇴",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-17T04:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "J"
  },
  {
    "id": 21,
    "home_team": "Portugal",
    "away_team": "DR Congo",
    "home_flag": "🇵🇹",
    "away_flag": "🇨🇩",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-17T17:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "L"
  },
  {
    "id": 22,
    "home_team": "England",
    "away_team": "Croatia",
    "home_flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "away_flag": "🇭🇷",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-17T20:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "K"
  },
  {
    "id": 23,
    "home_team": "Ghana",
    "away_team": "Panama",
    "home_flag": "🇬🇭",
    "away_flag": "🇵🇦",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-17T23:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "K"
  },
  {
    "id": 24,
    "home_team": "Uzbekistan",
    "away_team": "Colombia",
    "home_flag": "🇺🇿",
    "away_flag": "🇨🇴",
    "stage": "group_stage",
    "match_day": 1,
    "scheduled_at": "2026-06-18T02:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "L"
  },
  {
    "id": 25,
    "home_team": "Czechia",
    "away_team": "South Africa",
    "home_flag": "🇨🇿",
    "away_flag": "🇿🇦",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-18T16:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "A"
  },
  {
    "id": 26,
    "home_team": "Switzerland",
    "away_team": "Bosnia-Herzegovina",
    "home_flag": "🇨🇭",
    "away_flag": "🇧🇦",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-18T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "B"
  },
  {
    "id": 27,
    "home_team": "Canada",
    "away_team": "Qatar",
    "home_flag": "🇨🇦",
    "away_flag": "🇶🇦",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-18T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "B"
  },
  {
    "id": 28,
    "home_team": "Mexico",
    "away_team": "Korea Republic",
    "home_flag": "🇲🇽",
    "away_flag": "🇰🇷",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-19T03:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "A"
  },
  {
    "id": 29,
    "home_team": "United States",
    "away_team": "Australia",
    "home_flag": "🇺🇸",
    "away_flag": "🇦🇺",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-19T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "C"
  },
  {
    "id": 30,
    "home_team": "Scotland",
    "away_team": "Morocco",
    "home_flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "away_flag": "🇲🇦",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-19T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "F"
  },
  {
    "id": 31,
    "home_team": "Brazil",
    "away_team": "Haiti",
    "home_flag": "🇧🇷",
    "away_flag": "🇭🇹",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-20T01:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "F"
  },
  {
    "id": 32,
    "home_team": "Türkiye",
    "away_team": "Paraguay",
    "home_flag": "🇹🇷",
    "away_flag": "🇵🇾",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-20T04:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "C"
  },
  {
    "id": 33,
    "home_team": "Netherlands",
    "away_team": "Sweden",
    "home_flag": "🇳🇱",
    "away_flag": "🇸🇪",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-20T17:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "E"
  },
  {
    "id": 34,
    "home_team": "Germany",
    "away_team": "Ivory Coast",
    "home_flag": "🇩🇪",
    "away_flag": "🇨🇮",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-20T20:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "D"
  },
  {
    "id": 35,
    "home_team": "Ecuador",
    "away_team": "Curaçao",
    "home_flag": "🇪🇨",
    "away_flag": "🇨🇼",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-21T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "D"
  },
  {
    "id": 36,
    "home_team": "Tunisia",
    "away_team": "Japan",
    "home_flag": "🇹🇳",
    "away_flag": "🇯🇵",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-21T04:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "E"
  },
  {
    "id": 37,
    "home_team": "Spain",
    "away_team": "Saudi Arabia",
    "home_flag": "🇪🇸",
    "away_flag": "🇸🇦",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-21T16:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "G"
  },
  {
    "id": 38,
    "home_team": "Belgium",
    "away_team": "Iran",
    "home_flag": "🇧🇪",
    "away_flag": "🇮🇷",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-21T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "H"
  },
  {
    "id": 39,
    "home_team": "Uruguay",
    "away_team": "Cape Verde",
    "home_flag": "🇺🇾",
    "away_flag": "🇨🇻",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-21T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "G"
  },
  {
    "id": 40,
    "home_team": "New Zealand",
    "away_team": "Egypt",
    "home_flag": "🇳🇿",
    "away_flag": "🇪🇬",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-22T01:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "H"
  },
  {
    "id": 41,
    "home_team": "Argentina",
    "away_team": "Austria",
    "home_flag": "🇦🇷",
    "away_flag": "🇦🇹",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-22T17:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "J"
  },
  {
    "id": 42,
    "home_team": "France",
    "away_team": "Iraq",
    "home_flag": "🇫🇷",
    "away_flag": "🇮🇶",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-22T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "I"
  },
  {
    "id": 43,
    "home_team": "Norway",
    "away_team": "Senegal",
    "home_flag": "🇳🇴",
    "away_flag": "🇸🇳",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-23T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "I"
  },
  {
    "id": 44,
    "home_team": "Jordan",
    "away_team": "Algeria",
    "home_flag": "🇯🇴",
    "away_flag": "🇩🇿",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-23T03:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "J"
  },
  {
    "id": 45,
    "home_team": "Portugal",
    "away_team": "Uzbekistan",
    "home_flag": "🇵🇹",
    "away_flag": "🇺🇿",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-23T17:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "L"
  },
  {
    "id": 46,
    "home_team": "England",
    "away_team": "Ghana",
    "home_flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "away_flag": "🇬🇭",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-23T20:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "K"
  },
  {
    "id": 47,
    "home_team": "Panama",
    "away_team": "Croatia",
    "home_flag": "🇵🇦",
    "away_flag": "🇭🇷",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-23T23:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "K"
  },
  {
    "id": 48,
    "home_team": "Colombia",
    "away_team": "DR Congo",
    "home_flag": "🇨🇴",
    "away_flag": "🇨🇩",
    "stage": "group_stage",
    "match_day": 2,
    "scheduled_at": "2026-06-24T02:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "L"
  },
  {
    "id": 50,
    "home_team": "Bosnia-Herzegovina",
    "away_team": "Qatar",
    "home_flag": "🇧🇦",
    "away_flag": "🇶🇦",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-24T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "B"
  },
  {
    "id": 49,
    "home_team": "Switzerland",
    "away_team": "Canada",
    "home_flag": "🇨🇭",
    "away_flag": "🇨🇦",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-24T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "B"
  },
  {
    "id": 52,
    "home_team": "Morocco",
    "away_team": "Haiti",
    "home_flag": "🇲🇦",
    "away_flag": "🇭🇹",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-24T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "F"
  },
  {
    "id": 51,
    "home_team": "Scotland",
    "away_team": "Brazil",
    "home_flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "away_flag": "🇧🇷",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-24T22:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "F"
  },
  {
    "id": 53,
    "home_team": "Czechia",
    "away_team": "Mexico",
    "home_flag": "🇨🇿",
    "away_flag": "🇲🇽",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-25T01:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "A"
  },
  {
    "id": 54,
    "home_team": "South Africa",
    "away_team": "Korea Republic",
    "home_flag": "🇿🇦",
    "away_flag": "🇰🇷",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-25T01:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "A"
  },
  {
    "id": 56,
    "home_team": "Curaçao",
    "away_team": "Ivory Coast",
    "home_flag": "🇨🇼",
    "away_flag": "🇨🇮",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-25T20:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "D"
  },
  {
    "id": 55,
    "home_team": "Ecuador",
    "away_team": "Germany",
    "home_flag": "🇪🇨",
    "away_flag": "🇩🇪",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-25T20:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "D"
  },
  {
    "id": 57,
    "home_team": "Japan",
    "away_team": "Sweden",
    "home_flag": "🇯🇵",
    "away_flag": "🇸🇪",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-25T23:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "E"
  },
  {
    "id": 58,
    "home_team": "Tunisia",
    "away_team": "Netherlands",
    "home_flag": "🇹🇳",
    "away_flag": "🇳🇱",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-25T23:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "E"
  },
  {
    "id": 59,
    "home_team": "Türkiye",
    "away_team": "United States",
    "home_flag": "🇹🇷",
    "away_flag": "🇺🇸",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-26T02:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "C"
  },
  {
    "id": 60,
    "home_team": "Paraguay",
    "away_team": "Australia",
    "home_flag": "🇵🇾",
    "away_flag": "🇦🇺",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-26T02:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "C"
  },
  {
    "id": 62,
    "home_team": "Senegal",
    "away_team": "Iraq",
    "home_flag": "🇸🇳",
    "away_flag": "🇮🇶",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-26T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "I"
  },
  {
    "id": 61,
    "home_team": "Norway",
    "away_team": "France",
    "home_flag": "🇳🇴",
    "away_flag": "🇫🇷",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-26T19:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "I"
  },
  {
    "id": 63,
    "home_team": "Cape Verde",
    "away_team": "Saudi Arabia",
    "home_flag": "🇨🇻",
    "away_flag": "🇸🇦",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "G"
  },
  {
    "id": 64,
    "home_team": "Uruguay",
    "away_team": "Spain",
    "home_flag": "🇺🇾",
    "away_flag": "🇪🇸",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "G"
  },
  {
    "id": 66,
    "home_team": "New Zealand",
    "away_team": "Belgium",
    "home_flag": "🇳🇿",
    "away_flag": "🇧🇪",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T03:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "H"
  },
  {
    "id": 65,
    "home_team": "Egypt",
    "away_team": "Iran",
    "home_flag": "🇪🇬",
    "away_flag": "🇮🇷",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T03:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "H"
  },
  {
    "id": 68,
    "home_team": "Croatia",
    "away_team": "Ghana",
    "home_flag": "🇭🇷",
    "away_flag": "🇬🇭",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "K"
  },
  {
    "id": 67,
    "home_team": "Panama",
    "away_team": "England",
    "home_flag": "🇵🇦",
    "away_flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "K"
  },
  {
    "id": 69,
    "home_team": "Colombia",
    "away_team": "Portugal",
    "home_flag": "🇨🇴",
    "away_flag": "🇵🇹",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T23:30:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "L"
  },
  {
    "id": 70,
    "home_team": "DR Congo",
    "away_team": "Uzbekistan",
    "home_flag": "🇨🇩",
    "away_flag": "🇺🇿",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-27T23:30:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "L"
  },
  {
    "id": 72,
    "home_team": "Jordan",
    "away_team": "Argentina",
    "home_flag": "🇯🇴",
    "away_flag": "🇦🇷",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-28T02:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "J"
  },
  {
    "id": 71,
    "home_team": "Algeria",
    "away_team": "Austria",
    "home_flag": "🇩🇿",
    "away_flag": "🇦🇹",
    "stage": "group_stage",
    "match_day": 3,
    "scheduled_at": "2026-06-28T02:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": "J"
  },
  {
    "id": 73,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-28T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 74,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-28T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 75,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-29T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 76,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-29T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 77,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-29T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 78,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-30T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 79,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-30T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 80,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-06-30T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 81,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-01T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 82,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-01T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 83,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-01T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 84,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-02T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 85,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-02T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 86,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-02T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 87,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-03T00:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 88,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_32",
    "match_day": null,
    "scheduled_at": "2026-07-03T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 89,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-04T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 90,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-04T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 91,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-05T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 92,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-05T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 93,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-06T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 94,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-06T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 95,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-07T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 96,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "round_of_16",
    "match_day": null,
    "scheduled_at": "2026-07-07T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 97,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "quarterfinals",
    "match_day": null,
    "scheduled_at": "2026-07-10T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 98,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "quarterfinals",
    "match_day": null,
    "scheduled_at": "2026-07-10T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 99,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "quarterfinals",
    "match_day": null,
    "scheduled_at": "2026-07-12T18:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 100,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "quarterfinals",
    "match_day": null,
    "scheduled_at": "2026-07-12T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 101,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "semifinals",
    "match_day": null,
    "scheduled_at": "2026-07-14T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 102,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "semifinals",
    "match_day": null,
    "scheduled_at": "2026-07-15T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  },
  {
    "id": 103,
    "home_team": null,
    "away_team": null,
    "home_flag": null,
    "away_flag": null,
    "stage": "final",
    "match_day": null,
    "scheduled_at": "2026-07-19T21:00:00.000Z",
    "status": "scheduled",
    "home_score": null,
    "away_score": null,
    "group_name": null
  }
];
